### ISSUE TITLE
拍到的nft，进入该网页不能继续拍卖

### ISSUE THREAD

**Issue by woshiziye** [ArcBlock/nft-marketplace#4]
1、我用B竞价A的nft，拍卖成功
2、我在B的账户里打开nft的详情，然后点去拍卖，结果显示已卖出，而不能继续拍卖（作为新主人）
![image](https://user-images.githubusercontent.com/3413098/123978984-e3143f00-d9f2-11eb-997d-8829c4e658c3.png)

**Comment by wangshijun** [comment]
这个最新版已经 fix 了
